package com.example.backend.controllers;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.Map;

@RestController
@RequestMapping("/api/ai")
@CrossOrigin(origins = "*") // Allow React frontend
public class AIController {

    @GetMapping("/surprise-me")
    public ResponseEntity<?> surpriseMe() {
        // Phase 2: Call Gemini API to generate a trending destination, dates, and vibe
        return ResponseEntity.ok().body(Map.of(
            "destinationCity", "To be generated by Gemini (Phase 2)",
            "vibe", "To be generated by Gemini",
            "message", "AI Integration planned for Phase 2"
        ));
    }

    @PostMapping("/packing-list")
    public ResponseEntity<?> getPackingList(@RequestBody Map<String, String> request) {
        // Phase 2: Call Gemini API using destination, vibe, and weather to generate checklist
        return ResponseEntity.ok().body("AI Packing list generation planned for Phase 2 based on: " + request.get("vibe"));
    }
}
